Enable DSN configuration via environment.
dataflake/Products.ZPsycopgDA pull request #2
Opened 2023-09-15 08:44 UTC by sallner

A client (@sweh) uses environment variables to store the connection strings and distribute it across different instances. This patch enables the option to read the connection string from the environment variable if a prefix (`ENV:`) is used.

Would you consider this change valid? The package will be used in the future.

2023-09-15 14:48 UTC, sallner commented
@dataflake Maybe the tests have to be manually activated again.

2023-09-15 15:24 UTC, dataflake commented
I re-enabled the tests, please try again. They may not run because this is from a fork? I cannot spend much time on this, I am going on vacation tomorrow.

2023-09-27 11:34 UTC, icemac commented
@dataflake Could you please hit the approve workflow run button?

2023-10-02 15:22 UTC, dataflake requested changes
Small typo fix please.

2023-10-02 15:22 UTC, dataflake commented on CHANGES.rst
> +- Add support for reading the connection string from an environemt variable.
```suggestion
- Add support for reading the connection string from an environment variable.
```

2023-10-04 06:09 UTC, dataflake approved these changes

2023-10-04 06:13 UTC, merged

2023-10-04 06:18 UTC, dataflake commented
Release 4.1 with these changes is now published.

2023-10-04 07:23 UTC, sweh commented
Thank you!!!